export default {
  results: [
    {
      popularity: 51.156,
      vote_count: 180,
      video: false,
      poster_path: "/n2C6jRK9PtPIs99RQhKtqGlsnsO.jpg",
      id: 592834,
      adult: false,
      backdrop_path: "/yalJdTsb6EcDX5devj2ltWXuceO.jpg",
      original_language: "en",
      original_title: "My Spy",
      genre_ids: [28, 35, 10751],
      title: "My Spy",
      vote_average: 6.9,
      overview:
        "A hardened CIA operative finds himself at the mercy of a precocious 9-year-old girl, having been sent undercover to surveil her family.",
      release_date: "2020-04-17"
    },
    {
      popularity: 38.314,
      vote_count: 12,
      video: false,
      poster_path: "/7bjTzPQUV2KVI0HdUjf1l8lUoLF.jpg",
      id: 571265,
      adult: false,
      backdrop_path: "/ApywEWLRVaHUY5QX5tUhErBD5m3.jpg",
      original_language: "ja",
      original_title: "デジモンアドベンチャー LAST EVOLUTION 絆",
      genre_ids: [28, 12, 16, 14, 53],
      title: "Digimon Adventure: Last Evolution Kizuna",
      vote_average: 4.9,
      overview:
        "Tai is now a university student, living alone, working hard at school, and working every day, but with his future still undecided. Meanwhile, Matt and others continue to work on Digimon incidents and activities that help people with their partner Digimon. When an unprecedented phenomenon occurs, the DigiDestined discover that when they grow up, their relationship with their partner Digimon will come closer to an end.  As a countdown timer activates on the Digivice, they realize that the more they fight with their partner Digimon, the faster their bond breaks. Will they fight for others and lose their partner? The time to choose and decide is approaching fast. There is a short time before “chosen children” will become adults. This is the last adventure of Tai and Agumon.",
      release_date: "2020-03-25"
    },
    {
      popularity: 36.236,
      vote_count: 4,
      video: false,
      poster_path: "/vG8qBkByy9naORB6zahcntIC2N.jpg",
      id: 679796,
      adult: false,
      backdrop_path: "/2KCj021waxpTBg76s5i2YPEbzla.jpg",
      original_language: "en",
      original_title: "Enemy Lines",
      genre_ids: [28, 10752],
      title: "Enemy Lines",
      vote_average: 8.4,
      overview:
        "In the frozen, war torn landscape of occupied Poland during World War II, a crack team of allied commandos are sent on a deadly mission behind enemy lines to extract a rocket scientist from the hands of the Nazis.",
      release_date: "2020-04-24"
    },
    {
      popularity: 22.439,
      vote_count: 0,
      video: false,
      poster_path: "/vyHPaQ43CcNirWm2Q0sAsmFRY7f.jpg",
      id: 579400,
      adult: false,
      backdrop_path: "/5NUzfzdMzdHULAlk4ynrMP5vIrR.jpg",
      original_language: "en",
      original_title: "Stardust",
      genre_ids: [18],
      title: "Stardust",
      vote_average: 0,
      overview:
        "David Bowie went to America for the first time to promote his third album, The Man Who Sold the World. There, he embarked on a coast-to-coast publicity tour. During this tour, Bowie came up with the idea of his iconic Ziggy Stardust character, inspired by artists like Iggy Pop and Lou Reed.",
      release_date: "2020-05-01"
    },
    {
      popularity: 20.359,
      vote_count: 8,
      video: false,
      poster_path: "/1dugrX6FwRuN3miHi9yWqJumOYz.jpg",
      id: 684139,
      adult: false,
      backdrop_path: "/rHTmrP2D9N2XNlFdHVHw0F2cf4h.jpg",
      original_language: "en",
      original_title: "Behind You",
      genre_ids: [27],
      title: "Behind You",
      vote_average: 6,
      overview:
        "Two young sisters find that all the mirrors in their estranged aunt's house are covered or hidden. When one of them happens upon a mirror in the basement, she unknowingly releases a malicious demon.",
      release_date: "2020-04-17"
    },
    {
      popularity: 19.085,
      vote_count: 34,
      video: false,
      poster_path: "/eVyESHnWiTY1el8DEWbYMVW3K5k.jpg",
      id: 501395,
      adult: false,
      backdrop_path: "/z5LyKarB6baPF5PU10TD95NI8aU.jpg",
      original_language: "en",
      original_title: "True History of the Kelly Gang",
      genre_ids: [80, 18],
      title: "True History of the Kelly Gang",
      vote_average: 6.4,
      overview:
        "Set against the badlands of colonial Australia where the English rule with a bloody fist and the Irish endure, Ned Kelly discovers he comes from a line of Irish rebels—an uncompromising army of cross dressing bandits immortalised for terrorising their oppressors back in Ireland. Nurtured by the notorious bushranger, Harry Power and fuelled by the unfair arrest of his mother, Kelly recruits a wild bunch of warriors to plot one of the most audacious attacks of anarchy and rebellion the country has ever seen.",
      release_date: "2020-04-24"
    },
    {
      popularity: 19.072,
      vote_count: 1,
      video: false,
      poster_path: "/5mCqEeBA0MW7H6akFrFQXJu68rU.jpg",
      id: 550231,
      adult: false,
      backdrop_path: "/zRc6SG8V8WTTDrmZ78PgqjwYqoN.jpg",
      original_language: "en",
      original_title: "The Secret: Dare to Dream",
      genre_ids: [18],
      title: "The Secret: Dare to Dream",
      vote_average: 10,
      overview:
        "A widow with three children hires a handyman to fix her house during a major storm. When not doing home repairs, he shares his philosophy of believing in the power of the universe to deliver what we want.",
      release_date: "2020-04-17"
    },
    {
      popularity: 18.906,
      vote_count: 0,
      video: false,
      poster_path: "/eGHgHaujP6BqSCbfAHBuNWXXMOa.jpg",
      id: 661881,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "Home Sweet Home",
      genre_ids: [35, 18, 10749],
      title: "Home Sweet Home",
      vote_average: 0,
      overview:
        "Bored with her social butterfly lifestyle, Victoria Tremont longs to find that special someone. Naturally, when a handsome stranger walks into the coffee shop where she works, she turns on the charm. But when he fails to respond to her flirting the way men usually do, she’s perplexed. She finds out that he runs a ministry that builds affordable housing, and sees that if she wants to get his attention, all she has to do is volunteer. So what if it’s a faith-based ministry. Pretending to be a “church person” isn’t any different than pretending to like sports or a guy’s friends, right?",
      release_date: "2020-05-01"
    },
    {
      popularity: 17.677,
      id: 599396,
      video: false,
      vote_count: 3,
      vote_average: 7.3,
      title: "Axcellerator",
      release_date: "2020-04-08",
      original_language: "en",
      original_title: "Axcellerator",
      genre_ids: [878],
      backdrop_path: null,
      adult: false,
      overview:
        "When a young car thief stumbles on the invention of the century (and the various government agencies that want to kill him), he and a sassy checkout clerk named Kate have the adventure of a lifetime.",
      poster_path: "/wIcYosQoHBD8VrmxzrxSchTogjp.jpg"
    },
    {
      popularity: 17.346,
      vote_count: 0,
      video: false,
      poster_path: "/pdYiDj4POvQpGvXDhb4VJcdvLNc.jpg",
      id: 520318,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      original_title: "Fatima",
      genre_ids: [18, 10751],
      title: "Fatima",
      vote_average: 0,
      overview:
        "In 1917, outside the parish of Fátima, Portugal, a 10-year-old girl and her two younger cousins witness multiple visitations of the Virgin Mary, who tells them that only prayer and suffering will bring an end to World War I.  As secularist government officials and Church leaders try to force the children to recant their story, word of the sighting spreads across the country, inspiring religious pilgrims to flock to the site in hopes of witnessing a miracle..",
      release_date: "2020-04-24"
    },
    {
      popularity: 17.086,
      vote_count: 1,
      video: false,
      poster_path: "/oQTx93Ufi3RVhhLd7CAo9Kj00iK.jpg",
      id: 534134,
      adult: false,
      backdrop_path: "/jfbMyL3VGTU7MsDWSEbENid7lOy.jpg",
      original_language: "en",
      original_title: "Blackbird",
      genre_ids: [28, 80, 10749],
      title: "Blackbird",
      vote_average: 6,
      overview:
        'Troubled secret agent "Blackbird" abruptly retires from service and opens a luxurious nightclub in the Caribbean to escape the dark shadows of his past. An old flame arrives and reignites love in his life but she brings danger with her.',
      release_date: "2020-05-02"
    },
    {
      popularity: 16.873,
      vote_count: 817,
      video: false,
      poster_path: "/dhgW1uGaRj8vIgq54VnCP96X7Sv.jpg",
      id: 592,
      adult: false,
      backdrop_path: "/s7yfiwIshKQIT6M8ZcTnFKXHs8B.jpg",
      original_language: "en",
      original_title: "The Conversation",
      genre_ids: [80, 18, 9648],
      title: "The Conversation",
      vote_average: 7.6,
      overview:
        "Surveillance expert Harry Caul is hired by a mysterious client's brusque aide to tail a young couple. Tracking the pair through San Francisco's Union Square, Caul and his associate Stan manage to record a cryptic conversation between them. Tormented by memories of a previous case that ended badly, Caul becomes obsessed with the resulting tape, trying to determine if the couple are in danger.",
      release_date: "2020-03-20"
    },
    {
      popularity: 16.4,
      vote_count: 0,
      video: false,
      poster_path: "/aKrsLQcd6BRPzBQx2yLArAvv2UR.jpg",
      id: 675467,
      adult: false,
      backdrop_path: "/vzDXK5Q2BjDX1ZsBMUHuNRtlebC.jpg",
      original_language: "en",
      original_title: "John Lewis: Good Trouble",
      genre_ids: [99],
      title: "John Lewis: Good Trouble",
      vote_average: 0,
      overview:
        "Documentary chronicling John Lewis' 60-plus years of social activism and legislative action using interviews, rare archival footage.",
      release_date: "2020-05-01"
    },
    {
      popularity: 15.667,
      vote_count: 0,
      video: false,
      poster_path: "/zaecdNcjcVDiOcDcgQCOgHELSo0.jpg",
      id: 605804,
      adult: false,
      backdrop_path: "/mLX0UC1kV6BmYopkkSv0ox7AJgw.jpg",
      original_language: "en",
      original_title: "The Wretched",
      genre_ids: [27],
      title: "The Wretched",
      vote_average: 0,
      overview:
        "A rebellious teenage boy embarks on a gutsy crusade to stop the terrifying evil he suspects has possessed his neighbor in this bone-chilling occult thriller.",
      release_date: "2020-05-01"
    },
    {
      popularity: 15.143,
      vote_count: 17,
      video: false,
      poster_path: "/1UHrZxcewhGydsqrRF5Z6Qgqf6i.jpg",
      id: 617786,
      adult: false,
      backdrop_path: "/lxVf7wzanbz7m0mou7pUhokBYB.jpg",
      original_language: "en",
      original_title: "The Other Lamb",
      genre_ids: [18, 27, 53],
      title: "The Other Lamb",
      vote_average: 6.4,
      overview:
        "A haunting and nightmarish tale that tells the story of Selah, a young girl born into a repressive cult known as the Flock. The members of the Flock – all women and female children– live in a rural compound, and are led by one man, known only as Shepherd. Selah, a daughter who is on the cusp of teenage-hood, is given the great honor of participating in the sacred ritual of the birthing of the lambs – upon which they depend for survival – where she has a shocking and otherworldly experience. She begins to have strange visions that make her question her own reality, and everything the Shepherd has taught her and her sisters.",
      release_date: "2020-04-03"
    },
    {
      popularity: 15.002,
      vote_count: 8,
      video: false,
      poster_path: "/gKwXP1VvKNxrc1400yksKA4D9Qc.jpg",
      id: 617784,
      adult: false,
      backdrop_path: "/pPtBB9fD70Ta44pSQXGvZ6Kwc0p.jpg",
      original_language: "en",
      original_title: "Military Wives",
      genre_ids: [18],
      title: "Military Wives",
      vote_average: 8,
      overview:
        "Inspired by global phenomenon of military wives choirs, the story celebrates a band of misfit women who form a choir on a military base. As unexpected bonds of friendship flourish, music and laughter transform their lives, helping each other to overcome their fears for loved ones in combat.",
      release_date: "2020-03-27"
    },
    {
      popularity: 14.817,
      vote_count: 0,
      video: false,
      poster_path: "/4jhvgS0sOisNa0kGr8pRE3ZEhCa.jpg",
      id: 463870,
      adult: false,
      backdrop_path: "/fxlaoi2HvunBp3gBY1btRDWPe84.jpg",
      original_language: "en",
      original_title: "Altar Rock",
      genre_ids: [53],
      title: "Altar Rock",
      vote_average: 0,
      overview: "A thriller inspired by the Boston Marathon bombing in 2013.",
      release_date: "2020-05-02"
    },
    {
      popularity: 14.76,
      vote_count: 0,
      video: false,
      poster_path: "/d7LKwASjH0rgbSIz0eqUbzHZWe3.jpg",
      id: 695568,
      adult: false,
      backdrop_path: "/cJuCwQCVNNj571Fi7CiAb7lm6x2.jpg",
      original_language: "en",
      original_title: "Finding Grace",
      genre_ids: [18],
      title: "Finding Grace",
      vote_average: 0,
      overview:
        "Alaska Rose (Paris Warner), a troubled teenage girl whose mother left her and her family, has her life turned upside down when she is forced by a Judge (Erin Gray) to provide community service in a retirement home. As she develops a close friendship with Julianna Foster (Kisha Sharon Oglesby), one of the residents, she learns that giving is greater than receiving and she is forever changed when she discovers the power of family, hope, and faith through the strength of her devoted single father Conner (Jasen Wade).",
      release_date: "2020-04-21"
    },
    {
      popularity: 14.166,
      vote_count: 9,
      video: false,
      poster_path: "/y5QXP7qdwtPRiZy6cQTjRoaTXuW.jpg",
      id: 673159,
      adult: false,
      backdrop_path: "/raiiGiChImDhI6ORBK7zXNLTpN8.jpg",
      original_language: "en",
      original_title: "Hooking Up",
      genre_ids: [35, 18],
      title: "Hooking Up",
      vote_average: 8,
      overview:
        "Bailey and Darla embark upon a misguided and mutually deceitful form of therapy, one in which they must drive across the country re-enacting Darla's colorful history as a sex addict. As their true motivations for the road trip come to light, the unlikely pair force one another to confront their issues, discovering that there might actually be more to love than just sex.",
      release_date: "2020-03-20"
    },
    {
      popularity: 13.973,
      vote_count: 8,
      video: false,
      poster_path: "/6bMpRJl6pYoS97JdPLXjtJHCnfg.jpg",
      id: 646541,
      adult: false,
      backdrop_path: "/AmiBYDtBpOa2bgPCDNItCFU2wcT.jpg",
      original_language: "en",
      original_title: "In the Trap",
      genre_ids: [27, 53],
      title: "In the Trap",
      vote_average: 6.5,
      overview:
        "Philip, a solitary proof reader, is trapped in his apartment, too afraid to leave and tortured by an unknown evil force that has kept him prisoner for the last two years.",
      release_date: "2020-03-26"
    }
  ],
  page: 1,
  total_results: 81,
  dates: { maximum: "2020-05-05", minimum: "2020-03-18" },
  total_pages: 5
};
