export const FETCH_UPCOMING_MOVIES = "FETCH_UPCOMING_MOVIES";
export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES";
export const SET_POPULAR_MOVIES = "SET_POPULAR_MOVIES";
export const SET_UPCOMING_MOVIES = "SET_UPCOMING_MOVIES";
